### ISSUE TITLE
新增验证失败事件

### ISSUE THREAD

**Issue by BiggerWu** [yimijianfang/vue-drag-verify#1]
请问是否可以新增验证失败事件？

**Comment by yimijianfang** [comment]
> 请问是否可以新增验证失败事件？

安排，还请描述下应用场景

**Comment by BiggerWu** [comment]
我需要在用户验证失败的时候有一个事件可以调用，我可以自行在事件里定义。我可能会实现的场景：用户滑动失败，我重置图片缺口位置，重置图片旋转角度。

**Comment by BiggerWu** [comment]
还有希望你可以新增一个点击汉字或者字母的验证。

**Comment by yimijianfang** [comment]
> 我需要在用户验证失败的时候有一个事件可以调用，我可以自行在事件里定义。我可能会实现的场景：用户滑动失败，我重置图片缺口位置，重置图片旋转角度。这样进一步避免非法验证因为缺口位置或者旋转角度固定而进行遍历尝试位置。

好的，之前确实没想到，多谢反馈。

**Comment by yimijianfang** [comment]
> 还有希望你可以新增一个点击汉字或者字母的验证。

可以，会开发一个独立的组件。

**Comment by yimijianfang** [comment]
已新增`passfail`回调事件

**Comment by BiggerWu** [comment]
> 已新增`passfail`回调事件

请问你更新了npm上的组件了吗？昨天收到你更新的信息后，我尝试更新了一下组件，发现没有失败事件被触发，我查看了源码，好像没有看到passfail事件

**Comment by BiggerWu** [comment]
还有，请问能不能把生产环境中的console给去掉？

**Comment by yimijianfang** [comment]
> > 已新增`passfail`回调事件
> 
> 请问你更新了npm上的组件了吗？昨天收到你更新的信息后，我尝试更新了一下组件，发现没有失败事件被触发，我查看了源码，好像没有看到passfail事件

sorry，已经可以了。下次会修复打包后还有console的问题。另外与其他组件冲突的问题有时间贴下代码。

**Comment by yimijianfang** [comment]
> 还有，请问能不能把生产环境中的console给去掉？

版本v1.1.0打包后的console已去除
