### ISSUE TITLE
图片滑块组件(拼图)旋转图片滑块组件兼容问题

### ISSUE THREAD

**Issue by cuiliang0302** [yimijianfang/vue-drag-verify#10]
发现安卓手机自带的浏览器，使用图片滑块组件(拼图)和旋转图片滑块组件时存在兼容问题，滑动一小块距离就不能滑动了。![Screenshot_2021-05-25-09-28-08-934_com.android.browser.jpg](https://user-images.githubusercontent.com/42726109/119426286-8199ea00-bd3b-11eb-86b8-822dda3a27bc.jpg)

**Comment by yimijianfang** [comment]
感谢反馈，建议在dragMoving方法中阻止默认事件。下个版本会修复此问题
![image](https://user-images.githubusercontent.com/27459897/119429153-e3a91e00-bd40-11eb-8b1b-9baf9fea059a.png)
