### ISSUE TITLE
imgsrc

### ISSUE THREAD

**Issue by hadimajidi** [yimijianfang/vue-drag-verify#14]
it is a very nice plug-in
I made an src in the static folder and an img subfolder and I uploaded some pictures but it does not work. Could you please explain more about :imgsrc="img" in dragVerifyImgChip.

**Comment by yimijianfang** [comment]
**like this**

![image](https://user-images.githubusercontent.com/27459897/152717152-1ccdfbf9-de99-4efa-875f-f7a3d9b5ab69.png)
