### ISSUE TITLE
可能有一个组件冲突

### ISSUE THREAD

**Issue by BiggerWu** [yimijianfang/vue-drag-verify#2]
我在使用你的组件的时候可能碰到了一个组件冲突。
冲突组件：vuelidate(表单验证组件 )[组件地址](https://github.com/vuelidate/vuelidate) 
本地组件名：drag-verify-img
在调用drag-verify-img中的reset方法时，vuelidate组件出现了this.$options为undefined错误，本地组件出问题的代码在
` reImg: function() {
      this.$emit("update:isPassing", false); 
      const oriData = this.$options.data(); 
      for (const key in oriData) {
        if (oriData.hasOwnProperty(key)) {
          this.$set(this, key, oriData[key]);
        }
      }
      var handler = this.$refs.handler;
      var message = this.$refs.message;
      handler.style.left = "0";
      this.$refs.progressBar.style.width = "0";
      handler.children[0].className = this.handlerIcon;
      message.style["-webkit-text-fill-color"] = "transparent";
      message.style.animation = "slidetounlock 3s infinite";
      message.style.color = this.background;
      this.$refs.moveBar.style.left = "0px";
    },`
中，我分析后怀疑是for循环这一段
`  const oriData = this.$options.data(); 
      for (const key in oriData) {
        if (oriData.hasOwnProperty(key)) {
          this.$set(this, key, oriData[key]);
        }
      }`
出了问题，我现在强制修改了vuelidate的内容暂时是解决了问题。如果有兴趣可以试着修复一下问题，稍后我有时间会写一个可以复现这个问题的demo给你

**Comment by yulimchen** [comment]
> 我在使用你的组件的时候可能碰到了一个组件冲突。
> 冲突组件：vuelidate(表单验证组件 )[组件地址](https://github.com/vuelidate/vuelidate)
> 本地组件名：drag-verify-img
> 在调用drag-verify-img中的reset方法时，vuelidate组件出现了this.$options为undefined错误，本地组件出问题的代码在
> ` reImg: function() { this.$emit("update:isPassing", false); const oriData = this.$options.data(); for (const key in oriData) { if (oriData.hasOwnProperty(key)) { this.$set(this, key, oriData[key]); } } var handler = this.$refs.handler; var message = this.$refs.message; handler.style.left = "0"; this.$refs.progressBar.style.width = "0"; handler.children[0].className = this.handlerIcon; message.style["-webkit-text-fill-color"] = "transparent"; message.style.animation = "slidetounlock 3s infinite"; message.style.color = this.background; this.$refs.moveBar.style.left = "0px"; },`
> 中，我分析后怀疑是for循环这一段
> ` const oriData = this.$options.data(); for (const key in oriData) { if (oriData.hasOwnProperty(key)) { this.$set(this, key, oriData[key]); } }`
> 出了问题，我现在强制修改了vuelidate的内容暂时是解决了问题。如果有兴趣可以试着修复一下问题，稍后我有时间会写一个可以复现这个问题的demo给你

我这边保存 ESLint 直接报错了，参考这篇文章解决：[https://juejin.im/post/6844903881437085709](https://juejin.im/post/6844903881437085709)

**Comment by yimijianfang** [comment]
> > 我在使用你的组件的时候可能碰到了一个组件冲突。
> > 冲突组件：vuelidate(表单验证组件 )[组件地址](https://github.com/vuelidate/vuelidate)
> > 本地组件名：drag-verify-img
> > 在调用drag-verify-img中的reset方法时，vuelidate组件出现了this.$options为undefined错误，本地组件出问题的代码在
> > ` reImg: function() { this.$emit("update:isPassing", false); const oriData = this.$options.data(); for (const key in oriData) { if (oriData.hasOwnProperty(key)) { this.$set(this, key, oriData[key]); } } var handler = this.$refs.handler; var message = this.$refs.message; handler.style.left = "0"; this.$refs.progressBar.style.width = "0"; handler.children[0].className = this.handlerIcon; message.style["-webkit-text-fill-color"] = "transparent"; message.style.animation = "slidetounlock 3s infinite"; message.style.color = this.background; this.$refs.moveBar.style.left = "0px"; },`
> > 中，我分析后怀疑是for循环这一段
> > ` const oriData = this.$options.data(); for (const key in oriData) { if (oriData.hasOwnProperty(key)) { this.$set(this, key, oriData[key]); } }`
> > 出了问题，我现在强制修改了vuelidate的内容暂时是解决了问题。如果有兴趣可以试着修复一下问题，稍后我有时间会写一个可以复现这个问题的demo给你
> 
> 我这边保存 ESLint 直接报错了，参考这篇文章解决：https://juejin.im/post/6844903881437085709

谢谢反馈，已修复
