### ISSUE TITLE
图片滑块组件（拼图）显示问题

### ISSUE THREAD

**Issue by brucelpt** [yimijianfang/vue-drag-verify#3]
使用 F5 不断刷新界面，会发现图片滑块组件的小拼图部分不显示或者显示不全
![image](https://user-images.githubusercontent.com/37991444/101013418-37f7f000-359f-11eb-9e5c-509481917259.png)

**Comment by brucelpt** [comment]
环境
"vue": "2.6.10",
    "vue-count-to": "1.0.13",
    "vue-drag-verify-img-chip": "^1.1.0",
    "vue-drag-verify-img-rotate": "^1.1.0",
    "vue-drag-verify2": "^1.1.0",
    "vue-i18n": "7.3.2",
    "vue-router": "3.0.2",
    "vue-splitpane": "1.0.4",
    "vuedraggable": "2.20.0",
    "vuex": "3.1.0",

**Comment by brucelpt** [comment]
代码如下
<el-form-item>
        <drag-verify-img-chip
          ref="dragVerify"
          :imgsrc="img"
          :is-passing.sync="isPassing"
          :show-refresh="true"
          :width="width"
          text="请按住滑块拖动"
          success-text="验证通过"
          handler-icon="el-icon-d-arrow-right"
          success-icon="el-icon-circle-check"
          @refresh="reimg"
          @passcallback="pass"
        />
      </el-form-item>

import dragVerifyImgChip from 'vue-drag-verify-img-chip'
 components: { dragVerifyImgChip },


// 验证滑块参数
      isPassing: null,
      img: '/t3.png',
      width: 448


pass() {
    },
    reimg() {
    },

**Comment by brucelpt** [comment]
经测试，是由于设置了 :width="width" 这个参数导致的，页面没有报错

**Comment by yimijianfang** [comment]
> 经测试，是由于设置了 :width="width" 这个参数导致的，页面没有报错

所以现在没问题了，是吗

**Comment by brucelpt** [comment]
有问题啊，我只是不使用图片滑块了。因为现在的问题让我无法使用他，宽度只能使用默认不能修改，一旦修改，就会出现滑块不显示的问题

**Comment by yimijianfang** [comment]
> 有问题啊，我只是不使用图片滑块了。因为现在的问题让我无法使用他，宽度只能使用默认不能修改，一旦修改，就会出现滑块不显示的问题

源码和npm包已更新，最新版本是vue-drag-verify-img-chip@1.1.1
