### ISSUE TITLE
快速滑动会出现，滑块未到显示验证成功

### ISSUE THREAD

**Issue by wanru97** [yimijianfang/vue-drag-verify#4]
快速滑动会出现，滑块未到显示验证成功
https://i.postimg.cc/qvM1NjJW/checker.jpg

**Comment by yimijianfang** [comment]
> 快速滑动会出现，滑块未到显示验证成功
> https://i.postimg.cc/qvM1NjJW/checker.jpg

有设置user-select: none吗？

**Comment by wanru97** [comment]
我在引用组件的外层包裹了div，在这个div上面进行了设置user-select: none

**Comment by yimijianfang** [comment]
试试在html或body上加user-select: none
