### ISSUE TITLE
下载包了不需要import引入才能用的嘛？

### ISSUE THREAD

**Issue by xu-Aurora** [yimijianfang/vue-drag-verify#5]
不管是否import引入包，都报错，有使用的例子嘛？

**Comment by xu-Aurora** [comment]
width可以自适应嘛？或者100%，因为不同屏幕下需要适配，不能直接写死一个值

**Comment by yimijianfang** [comment]
需要import引入，使用参考：https://yimijianfang.github.io/vue-drag-verify/#/
width暂时不支持自适应，针对这种需求可以考虑在通过计算属性获取宽度相同元素的宽度
