### ISSUE TITLE
vue3+elementplus引入之后直接报一堆selfHook.bind is not a function的错误？

### ISSUE THREAD

**Issue by bruce-zhang932** [yimijianfang/vue-drag-verify#7]
我是先引入
npm i vue-drag-verify-img-chip -S
之后这样写：
![image](https://user-images.githubusercontent.com/11385973/113121629-6c29a780-9245-11eb-8e76-5cdf2c80e2d2.png)
![image](https://user-images.githubusercontent.com/11385973/113121676-78156980-9245-11eb-8fa0-0708f0677b70.png)
运行之后直接报一堆selfHook.bind is not a function的错误？

**Comment by yimijianfang** [comment]
组件暂不支持vue3。亲测可以通过手动引入`dragVerifyImgChip.vue`文件实现
**注意**因为vue3不支持`.sync`，在vue3中使用组件做以下调整
~~`:isPassing.sync="isPassing"`~~
`v-model:isPassing="isPassing"`

**Comment by syyzz3** [comment]
@yimijianfang 您好，”手动引入dragVerifyImgChip.vue文件“是什么意思？ 我换成v-model:isPassing="isPassing"还是报那个错误？

**Comment by syyzz3** [comment]
![image](https://user-images.githubusercontent.com/11385973/113251391-c5044900-92f4-11eb-871b-288afbb0f7d2.png)
您好，我手动引入后，没有图片也没有报错，是什么原因呢？

**Comment by yimijianfang** [comment]
看上面代码的截图，应该是没有引入图片，需要把图片文件赋值给`imgsrc`。
详见demo

**Comment by syyzz3** [comment]
又报了新的错误
![image](https://user-images.githubusercontent.com/11385973/113370920-a440ff80-9397-11eb-92ad-7e37ff7eb2ef.png)

![image](https://user-images.githubusercontent.com/11385973/113370834-7956ab80-9397-11eb-80b4-e103e5c2451d.png)
![image](https://user-images.githubusercontent.com/11385973/113370988-c5095500-9397-11eb-957b-7509cc520b62.png)
![image](https://user-images.githubusercontent.com/11385973/113371003-ce92bd00-9397-11eb-86fa-dbfc47ed1daf.png)

**Comment by yimijianfang** [comment]
前两天也发现这个错误了，更新最新的组件到本地。
![image](https://user-images.githubusercontent.com/27459897/113372601-a442fe80-939b-11eb-8492-27b9eacd63ba.png)

**Comment by syyzz3** [comment]
您好，刷新图片又遇到了一个问题，不知道是否是与vue3的冲突

![image](https://user-images.githubusercontent.com/11385973/113384965-bdf33e80-93b9-11eb-898c-d430c948c12f.png)
![image](https://user-images.githubusercontent.com/11385973/113384988-cb102d80-93b9-11eb-8a83-72a44723bc6f.png)
![image](https://user-images.githubusercontent.com/11385973/113385012-d3686880-93b9-11eb-8751-d579337efd92.png)

**Comment by yimijianfang** [comment]
Vue3不支持`$set`方法，可以修改`reImg`方法
~~this.$set(this, key, oriData[key])~~
**this[key] = oriData[key]**

**Comment by syyzz3** [comment]
@yimijianfang 您好，为啥您demo滑动验证通过滑块位置不会变，我引入这个为啥验证成功滑块位置就回到最左边了？
![image](https://user-images.githubusercontent.com/11385973/113647121-ccdd3800-96bc-11eb-9ee2-67b8fe57a03e.png)
![image](https://user-images.githubusercontent.com/11385973/113647234-057d1180-96bd-11eb-9589-f7135c88c3d0.png)

**Comment by yimijianfang** [comment]
此问题已修改
