### ISSUE TITLE
验证通过后滑块跑到了最开始的位置？

### ISSUE THREAD

**Issue by bruce-zhang932** [yimijianfang/vue-drag-verify#8]
![image](https://user-images.githubusercontent.com/11385973/113404342-995b8e80-93da-11eb-9c96-73cf8b005ee2.png)

**Comment by yimijianfang** [comment]
问题已解决，组件均已支持vue3

**Comment by bruce-zhang932** [comment]
@yimijianfang 您好，是什么问题导致的，我在源码里改了很多次，到最后都会莫名的跑到最开始

**Comment by yimijianfang** [comment]
> @yimijianfang 您好，是什么问题导致的，我在源码里改了很多次，到最后都会莫名的跑到最开始

删除了滑块css的默认值`left: "0px"`，其实我也不解，偶然发现的
